version: "3"

services:
  flaskapp:
    build: ./app
    container_name: myflaskapp
    restart: always
    # ports:
    #   - 5000:5000
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: flask_nginx
    restart: always
    ports:
      - 80:80